[package]
name = "shader-sense-cli"
description = "Command line interface for shader validation and symbol inspection"
version = "0.6.3"
repository = "https://github.com/antaalt/shader-sense"
keywords = ["shader", "validate", "hlsl", "glsl", "wgsl"]
categories = ["development-tools", "graphics"]
edition.workspace = true
license-file.workspace = true

[dependencies]
colored = "3.0.0"
shader-sense.workspace = true
