[target.wasm32-wasip1-threads]
# Single page size = 65536 bytes
rustflags = [
  "-C", "link-arg=--initial-memory=10485760", # 65 536 * 160
  # This is a lot, but necessary because glslang has a HUGE memory footprint...
  "-C", "link-arg=--max-memory=134217728", # 65 536 * 2048
  #"-C", "link-arg=--shared-memory",
  #"-C", "link-arg=--import-memory",
  #"-C", "link-arg=--export-memory",
]
runner = "wasmtime --wasi threads=y --dir ../shader-sense/test::/test"

[target.wasm32-unknown-unknown]
# Tree sitter is a C API with rust binding here, and linking rust & C for wasm32-unknown-unknown is impossible without this perma-unstable flag, available only in nightly rust.
# Will have to wait until the issue is fixed in wasm32-unknown-unknown, god knows when.
# https://stackoverflow.com/questions/78556000/how-you-can-link-a-rust-library-with-c-c-and-wasm-bindgen-for-the-wasm32-unkno
# https://github.com/rustwasm/wasm-bindgen/issues/3454
rustflags = ["-Z", "wasm-c-abi=spec"]

# Set this to your wasi-sdk compiler to avoid picking a clang version that does not support WASI (such as vs bundled version)
#[env]
#CC = "your/path/to/wasi-sdk/bin/clang.exe"
#CXX = "your/path/to/wasi-sdk/bin/clang++.exe"