[target.wasm32-wasip1-threads]
# Single page size = 65536 bytes
rustflags = [
  "-C", "link-arg=--initial-memory=10485760", # 65 536 * 160
  "-C", "link-arg=--max-memory=67108864", # 65 536 * 1024
  #"-C", "link-arg=--shared-memory",
  #"-C", "link-arg=--import-memory",
  #"-C", "link-arg=--export-memory",
]
# This config is only compatible with old versions of wasmtime...
runner = "wasmtime --dir ../shader-sense/test::/test --wasm-features=threads --wasi-modules=experimental-wasi-threads"
