[target.wasm32-wasip1-threads]
# Single page size = 65536 bytes
rustflags = [
  "-C", "link-arg=--initial-memory=13107200", # 65 536 * 200
  # This is a lot, but necessary because glslang has a HUGE memory footprint...
  "-C", "link-arg=--max-memory=134217728", # 65 536 * 2048
  #"-C", "link-arg=--shared-memory",
  #"-C", "link-arg=--import-memory",
  #"-C", "link-arg=--export-memory",
]
runner = "wasmtime --wasm shared-memory=y --wasi threads=y --dir ../shader-sense/test::/test"

[target.wasm32-unknown-unknown]
# Cannot build C and C++ to this target because there is no libc available.

# Set this to your wasi-sdk compiler to avoid picking a clang version that does not support WASI (such as vs bundled version)
# Ideally, set it in the global cargo config.toml to inherit there and avoid submitting it.
# You can download wasi-sdk here https://github.com/WebAssembly/wasi-sdk
#[env]
#CC_wasm32_wasip1_threads = "your/path/to/wasi-sdk/bin/clang.exe"
#CXX_wasm32_wasip1_threads = "your/path/to/wasi-sdk/bin/clang++.exe"
#WASI_SYSROOT= "your/path/to/wasi-sysroot"