name: Deploy Extension

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Required for release upload
      - name: Create release folder
        run: mkdir -p ./bin-windows/ && mkdir -p ./bin-linux/ && mkdir -p ./bin-wasi/
      - name: Download Windows x64 desktop binary
        uses: actions/download-artifact@v4
        with:
          name: shader-language-server-x86_64-pc-windows-msvc
          path: ./bin-windows
      - name: Download Linux x64 desktop binary
        uses: actions/download-artifact@v4
        with:
          name: shader-language-server-x86_64-unknown-linux-gnu
          path: ./bin-linux
      - name: Download WASI binary
        uses: actions/download-artifact@v4
        with:
          name: shader-language-server-wasm32-wasip1-threads
          path: ./bin-wasi
      - name: Download windows dxc dll.
        uses: robinraju/release-downloader@v1.11
        with:
          repository: 'microsoft/DirectXShaderCompiler'
          tag: v1.8.2405
          fileName: 'dxc_2024_05_24.zip'
          extract: true
          out-file-path: './dxc'
      - name: Download unix dxc dll.
        uses: robinraju/release-downloader@v1.11
        with:
          repository: 'microsoft/DirectXShaderCompiler'
          tag: v1.8.2405
          fileName: 'linux_dxc_2024_05_24.x86_64.tar.gz'
          extract: true
          out-file-path: './dxc-unix'
      - name: Copy dxc windows dll to bin.
        run: cp ./dxc/bin/x64/dxcompiler.dll ./bin-windows/dxcompiler.dll && cp ./dxc/bin/x64/dxil.dll ./bin-windows/dxil.dll
      - name: Copy dxc linux dynamic library to bin.
        run: cp ./dxc-unix/lib/libdxcompiler.so ./bin-linux/libdxcompiler.so && cp ./dxc-unix/lib/libdxil.so ./bin-linux/libdxil.so
      - name: Zip Windows binary
        run: zip -v -r -j shader-language-server-x86_64-pc-windows-msvc.zip ./bin-windows
      - name: Zip Linux binary
        run: zip -v -r -j shader-language-server-x86_64-unknown-linux-gnu.zip ./bin-linux
      - name: Zip WASI binary
        run: zip -v -r -j shader-language-server-wasm32-wasip1-threads.zip ./bin-wasi
      - name: Upload release build
        run: gh release upload ${{ github.ref_name }} shader-language-server-x86_64-pc-windows-msvc.zip shader-language-server-x86_64-unknown-linux-gnu.zip shader-language-server-wasm32-wasip1-threads.zip
        env:
          GH_TOKEN: ${{ github.token }}

  publish:
    runs-on: ubuntu-latest
    needs: deploy # Dont really need but keep to avoid issue on issues.
    # Skip pre-release because cargo dont support pre-release tag.
    if: ${{ !github.event.release.prerelease }}

    steps:
      - uses: actions/checkout@v4 # Required for release upload
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      # Publish workspace (sense+server), intrinsics parser is marked as private
      - uses: katyo/publish-crates@v2
        with:
          ignore-unpublished-changes: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}